### PR TITLE
Feature/reptiles page

### PR DESCRIPTION
**Pull request by Souad-Sud**
can you check again ?

### CODE REVIEW

**Review by bushra-rauf — COMMENTED** [review]
you have to add paragrah in js. Dobble check it please!

**Comment by Meazajao** [comment]
it looks nice very pretty work just need to add the js click back that i'm also trying to fix. I dont know if I already told you but the picture while doing the animation is covering the content, if its intentional then it fine just so you know.

**Review by Moshira89 — APPROVED** [review]
good

**Review by bushra-rauf — COMMENTED** [review]
its look good on desktop screen but on mobile screen as the sidebar is sticky its coming over  the image. Do you wanted like this ?

**Review by bushra-rauf — APPROVED** [review]
all good

**Pull request merged**
