### PR TITLE
Refactored the project structure and added responsiveness to the home…

### PR DESCRIPTION
**Pull request by bushra-rauf**
home-page

### CODE REVIEW

**Review by Moshira89 — APPROVED** [review]

**Comment by ranjithavelusamy** [comment]
u r editing this

**Review by ranjithavelusamy — APPROVED** [review]

**Comment by ranjithavelusamy** [comment]
hi lets check

**Review by ranjithavelusamy — APPROVED** [review]

**Comment by Souad-Sud** [comment]
your js is not included

**Review by Moshira89 — APPROVED** [review]
Tested

**Comment by bushra-rauf** [comment]
This is just the layout

**Pull request merged**
