### PR TITLE
final-header

### PR DESCRIPTION
**Pull request by ranjithavelusamy**

### CODE REVIEW

**Comment by Moshira89** [comment]
Good job.

**Comment by Souad-Sud** [comment]
looks fine

**Review by Souad-Sud — APPROVED** [review]

**Review by Moshira89 — APPROVED** [review]

**Review by Souad-Sud — APPROVED** [review]
looks good

**Review by Moshira89 — APPROVED** [review]

**Comment by Meazajao** [comment]
am I the only one seeing that its not responsive and the picture is to big.

**Pull request closed without merging**
