### PR TITLE
aboutteams

### PR DESCRIPTION
**Pull request by Moshira89**
AboutTeams page

### CODE REVIEW

**Comment by ranjithavelusamy** [comment]
yaa its good

**Review by ranjithavelusamy — APPROVED** [review]

**Review by bushra-rauf — COMMENTED** [review]
do you wanted the welcome images stay when clicked on name.

**Review by bushra-rauf — APPROVED** [review]
ok then good

**Comment by bushra-rauf** [comment]
your images are not displaying when the page load. It was coming. Can you please have a look and check the images path

**Pull request merged**
